## Server Properties
server:
  port: 8181
  compression:
    enabled: true

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#spring.datasource.url= jdbc:mysql://localhost:3306/polling_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#spring.datasource.userId= root
#spring.datasource.password=

#spring.datasource.url= jdbc:oracle:thin:@//10.5.16.106:1522/findb
#spring.datasource.userId= DFS
#spring.datasource.password=DFS.1234#
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver


#spring.datasource.initialize=true

spring:
  profiles:
    active: dev # dev, prod
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ## Jackson Properties
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

## hikari
#spring.datasource.hikari.connection-timeout=60000
#spring.datasource.hikari.maximum-pool-size=5

  ## App Properties
app:
  name: api
  authentication:
    jwtSecret: JWTSuperSecretKey
    jwtExpirationInMs: 1800000


## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServer2012Dialect

#spring.jpa.hibernate.ddl-auto = update

## Hibernate Logging
logging:
  level:
    org.hibernate.SQL: DEBUG



